class checkoutObjects{
    termOfServiceCheckBox = '#termsofservice'
    checkoutBtn = '#checkout'
    countryBillingAddress = '#BillingNewAddress_CountryId'
    stateBillingAddress = '#BillingNewAddress_StateProvinceId'
    cityBillingAddress = '#BillingNewAddress_City'
    address1BillingAddress = '#BillingNewAddress_Address1'
    zipCodeBillingAddress = '#BillingNewAddress_ZipPostalCode'
    phoneNoBillingAddress = '#BillingNewAddress_PhoneNumber'
    continueBtn = '#billing-buttons-container > .button-1' 
    continueBtn2 = '#payment-method-buttons-container > .button-1'
    continueBtn3 = '#payment-info-buttons-container > .button-1'
    CCPaymentMethod = '#paymentmethod_2'
    CCType = '#CreditCardType'
    cardholderNameTxt = '#CardholderName'
    cardNumberTxt = '#CardNumber'
    expireMonth = '#ExpireMonth'
    expireYear = '#ExpireYear'
    cardCode = '#CardCode'
    productNameLabel = '.product-name'
    confirmBtn = '#confirm-order-buttons-container > .button-1'
    orderSuccessfulLabel = 'strong'
    detailsOrderTxtBtn = '.details > :nth-child(2) > a'
}
export default checkoutObjects